name = "FastPKSim"
uuid = "b0ae6185-9f73-47b1-8c06-57e18f526c0d"
authors = ["Ylva Wahlquist <ylva.wahlquist@control.lth.se> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
